plugins {
    id 'maven-publish'
}

def unobfuscatedMinecraft = project.findProperty('unobfuscated_minecraft')?.toString()?.toBoolean() ?: false

if (unobfuscatedMinecraft) {
    apply plugin: 'net.fabricmc.fabric-loom'
} else {
    apply plugin: 'net.fabricmc.fabric-loom-remap'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/releases/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    if (unobfuscatedMinecraft) {
        implementation "net.fabricmc:fabric-loader:${project.loader_version}"
        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

        compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}") {
            transitive = false
        }
    } else {
        mappings loom.officialMojangMappings()
        modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

        modCompileOnly("com.terraformersmc:modmenu:${project.modmenu_version}") {
            transitive = false
        }
    }
}

processResources {
    def props = [
        version        : version,
        minecraft_dep  : project.minecraft_dep,
        loader_version : project.loader_version,
        java_version   : project.java_version
    ]

    inputs.properties(props)

    filesMatching('fabric.mod.json') {
        expand(props)
    }
}

def targetJava = (project.java_version as int)

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJava)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = targetJava
    options.encoding = 'UTF-8'
}

jar {
    def projectName = rootProject.name
    inputs.property 'projectName', projectName

    from(rootProject.file('LICENSE')) {
        rename { "${it}_${projectName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${project.archives_base_name}-mc${project.minecraft_version}"
            from components.java
        }
    }
}
