org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.configureondemand=true
dev.kikugie.stonecutter.hard_mode=true

loom_legacy_version=1.17.11
loom_modern_version=1.18-SNAPSHOT
loader_version=0.19.5
loader_min_version=0.19.0

mod_version=0.5.0-beta.2
maven_group=io.github.pma10
archives_base_name=server-profile
