org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.141.6+1.21.11
modmenu_version=cLkYaVuL

mod_version=0.3.0-beta.2
maven_group=io.github.pma10
archives_base_name=server-profiles
